apiVersion: apps/v1
kind: Deployment
metadata:
  name: rp-pods
  labels:
    app: yellowapp
    env: dev
  namespace: devnamespace
spec:
  minReadySeconds: 6
  replicas: 4
  selector:
    matchExpressions:
      - key: web
        operator: In
        values:
          - yellowapp-pods
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      name: podlevellabels
      labels:
        web: yellowapp-pods
        env: prod
        frontend: web
    spec:
      containers:
        - name: yellowimage
          image: pavan01234567/myownimage:vil
          ports:
            - containerPort: 80
              protocol: TCP
          startupProbe:
            httpGet:
              path: /
              port: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
          resources:
            requests:
              cpu: "400m"
              memory: "2500Mi"
            limits:
              cpu: "1800m"
              memory: "7500Mi"
